services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: payment_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8006:8006"
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/payment_service_db

volumes:
  postgres_data: